version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storefront-backend
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  db-test:
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storefront-backend-test
    ports:
      - '5433:5432'

volumes:
  postgres: