/* Replace with your SQL commands */

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    price money NOT NULL,
    category VARCHAR(150),
    description text,
    url text,
    selled integer DEFAULT 0
);

INSERT INTO products (name, price, category, description, url) VALUES ('Platinum End - Manga', 10.99, 'book', 'Ever since he lost his family in an explosion, Mirai Kakehashi has lived a life of pain and despair. Every day, he endures abuse at the hands of relatives who took him in. As his anguish steadily chips away at his will to live, he is eventually pushed to the brink. Prepared to throw it all away, he stands on the edge of a precipice and takes the leap. However, instead of falling to his death, he enters a trance where he meets a winged being who claims to be his guardian angel. Named Nasse, the angel offers him two priceless abilities and convinces him to go on living. When Mirai experiences the marvel of his new powers firsthand, he gets a taste of the freedom that was locked away from him for so long. Armed with Nasse gifts, Mirai is flung into a showdown with 12 other individuals, one of which will be chosen to become the next God. In stark contrast to when he wanted to end his life, Mirai is now prepared to do whatever it takes to protect his bleak chance at happiness, lest it be wrenched from his grasp forever.', 'https://upload.wikimedia.org/wikipedia/en/8/85/Platinum_End_Volume_1.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('Berserk: The Prototype - Manga', 8.99, 'book', 'Guts, a former mercenary now known as the "Black Swordsman," is out for revenge. After a tumultuous childhood, he finally finds someone he respects and believes he can trust, only to have everything fall apart when this person takes away everything important to Guts for the purpose of fulfilling his own desires. Now marked for death, Guts becomes condemned to a fate in which he is relentlessly pursued by demonic beings. Setting out on a dreadful quest riddled with misfortune, Guts, armed with a massive sword and monstrous strength, will let nothing stop him, not even death itself, until he is finally able to take the head of the one who stripped him—and his loved one—of their humanity.', 'https://cdn.myanimelist.net/images/manga/1/157897.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('One Piece - Manga', 14.99, 'book', 'Gol D. Roger, a man referred to as the "Pirate King," is set to be executed by the World Government. But just before his demise, he confirms the existence of a great treasure, One Piece, located somewhere within the vast ocean known as the Grand Line. Announcing that One Piece can be claimed by anyone worthy enough to reach it, the Pirate King is executed and the Great Age of Pirates begins. Twenty-two years later, a young man by the name of Monkey D. Luffy is ready to embark on his own adventure, searching for One Piece and striving to become the new Pirate King. Armed with just a straw hat, a small boat, and an elastic body, he sets out on a fantastic journey to gather his own crew and a worthy ship that will take them across the Grand Line to claim the greatest status on the high seas.', 'https://cdn.myanimelist.net/images/manga/3/55539.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('Full Metal Alchemist - Manga', 5.99, 'book', 'Alchemists are knowledgeable and naturally talented individuals who can manipulate and modify matter due to their art. Yet despite the wide range of possibilities, alchemy is not as all-powerful as most would believe. Human transmutation is strictly forbidden, and whoever attempts it risks severe consequences. Even so, siblings Edward and Alphonse Elric decide to ignore this great taboo and bring their mother back to life. Unfortunately, not only do they fail in resurrecting her, they also pay an extremely high price for their arrogance: Edward loses his left leg and Alphonse his entire body. Furthermore, Edward also gives up his right arm in order to seal his brother soul into a suit of armor.', 'https://cdn.myanimelist.net/images/manga/3/243675.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('Grand Blue - Manga', 10.99, 'book', 'Among the seaside town of Izu ocean waves and rays of shining sun, Iori Kitahara is just beginning his freshman year at Izu University. As he moves into his uncle scuba diving shop, Grand Blue, he eagerly anticipates his dream college life, filled with beautiful girls and good friends.', 'https://cdn.myanimelist.net/images/manga/2/166124.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('JoJos Bizarre Adventure - Manga', 14.99, 'book', 'In the American Old West, the world greatest race is about to begin. Thousands line up in San Diego to travel over six thousand kilometers for a chance to win the grand prize of fifty million dollars. With the era of the horse reaching its end, contestants are allowed to use any kind of vehicle they wish. Competitors will have to endure grueling conditions, traveling up to a hundred kilometers a day through uncharted wastelands. The Steel Ball Run is truly a one-of-a-kind event.', 'https://cdn.myanimelist.net/images/manga/3/179882.jpg');
INSERT INTO products (name, price, category, description, url) VALUES ('Vagabond - Manga', 4.99, 'book', 'In 16th-century Japan, Shinmen Takezou is a wild, rough young man, in both his appearance and his actions. His aggressive nature has won him the collective reproach and fear of his village, leading him and his best friend, Matahachi Honiden, to run away in search of something grander than provincial life. The pair enlist in the Toyotomi army, yearning for glory—but when the Toyotomi suffer a crushing defeat at the hands of the Tokugawa Clan at the Battle of Sekigahara, the friends barely make it out alive.', 'https://cdn.myanimelist.net/images/manga/2/181787.jpg');